### ISSUE TITLE
Template:Production display owl:sameAs

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#86]
ex: http://data.performing-arts.ch/w/6928a7dc-496c-42e4-a171-d4734164b9a9

**Comment by fkraeutli** [comment]
owl:sameAs present in statements but not displayed in template

**Comment by olyanicolaeva** [comment]
**Analysis** 
When trying to reproduce the issue, I see that it is a problem with this particular record while other records are displaying external links module correctly.
There are only two records of type F25_Performance_Plan, which have _sameAs_ relations:
- [http://data.performing-arts.ch/w/6928a7dc-496c-42e4-a171-d4734164b9a9](http://data.performing-arts.ch/w/6928a7dc-496c-42e4-a171-d4734164b9a9)
- [http://data.performing-arts.ch/w/3a2762f2-d69b-42cf-9cef-54c9742cb923](http://data.performing-arts.ch/w/3a2762f2-d69b-42cf-9cef-54c9742cb923)

The second record displays the relation _sameAs_ in the template.
Templates of other entity types, e.g. Persons, show the external links module correctly.

**Problem**
The problem is in the invalid format of the external identifier link: https://www.wikidata.org/wiki/Q111722329
Accepted format in the external links template:
```
http://www.wikidata.org/**entity/** + Wiki ID number
https://www.wikidata.org**/entity/** + Wiki ID number
```
When the format is corrected  from https://www.wikidata.org/wiki/Q111722329 to https://www.wikidata.org/entity/Q111722329 the template is rendered correctly.
<img width="1299" alt="Screenshot 2023-02-08 at 14 58 26" src="https://user-images.githubusercontent.com/86773892/217550475-01845b9b-905b-4d5c-8e40-00596d3e63c5.png">

**Solution**
@b2d3c would you like to correct the data or should we add **http://www.wikidata.org/wiki/** into allowed formats?

**Comment by b2d3c** [comment]
Thanks @olyanicolaeva ! I understand. I will correct it. We stay with the Wikidata URI form only accepted.
